# Generated by Django 5.2.7 on 2025-10-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('title', models.CharField(help_text='Ej: Abogado de Familia', max_length=100, verbose_name='Título')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('profile_picture_url', models.URLField(blank=True, verbose_name='URL Foto de Perfil')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Ej: 573001234567', max_length=20, verbose_name='Número WhatsApp')),
                ('instagram_username', models.CharField(blank=True, help_text='Solo el usuario, sin @', max_length=50, verbose_name='Usuario Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('website_url', models.URLField(blank=True, verbose_name='URL Sitio Web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Perfil Activo')),
            ],
        ),
    ]
